# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PMonitor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePMonitor.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\nCpuMessage\x12\x0c\n\x04load\x18\x01 \x01(\x01\"/\n\nMemMessage\x12\x0f\n\x07mem_use\x18\x01 \x01(\x01\x12\x10\n\x08mem_rate\x18\x02 \x01(\x01\":\n\nNetMessage\x12\x15\n\rnet_recv_Rate\x18\x01 \x01(\x01\x12\x15\n\rnet_send_Rate\x18\x02 \x01(\x01\"\x99\x01\n\x0eProcessMessage\x12\x11\n\tproc_Name\x18\x01 \x01(\t\x12\x11\n\tisRunning\x18\x02 \x01(\x08\x12\x10\n\x08\x63pu_load\x18\x03 \x01(\x01\x12\x10\n\x08mem_load\x18\x04 \x01(\x01\x12\x0f\n\x07mem_use\x18\x05 \x01(\x01\x12\x15\n\rnet_recv_Rate\x18\x06 \x01(\x01\x12\x15\n\rnet_send_Rate\x18\x07 \x01(\x01\"\x81\x01\n\x0eMonitorMessage\x12\x19\n\x04\x63pum\x18\x01 \x01(\x0b\x32\x0b.CpuMessage\x12\x19\n\x04memm\x18\x02 \x01(\x0b\x32\x0b.MemMessage\x12\x19\n\x04netm\x18\x03 \x01(\x0b\x32\x0b.NetMessage\x12\x1e\n\x05procm\x18\x04 \x03(\x0b\x32\x0f.ProcessMessage\"3\n\x12ProcMonitorRequest\x12\x0f\n\x07\x61\x64\x64_del\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x03(\t\"\x1c\n\x08ShellExe\x12\x10\n\x08shellnum\x18\x01 \x01(\x05\x32\xc3\x01\n\x0bGrpcService\x12:\n\x0bMonitorTick\x12\x16.google.protobuf.Empty\x1a\x0f.MonitorMessage\"\x00\x30\x01\x12\x43\n\x12ProcessMonitorCtrl\x12\x13.ProcMonitorRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x33\n\x0cShellControl\x12\t.ShellExe\x1a\x16.google.protobuf.Empty\"\x00\x42\x03\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PMonitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000'
  _globals['_CPUMESSAGE']._serialized_start=47
  _globals['_CPUMESSAGE']._serialized_end=73
  _globals['_MEMMESSAGE']._serialized_start=75
  _globals['_MEMMESSAGE']._serialized_end=122
  _globals['_NETMESSAGE']._serialized_start=124
  _globals['_NETMESSAGE']._serialized_end=182
  _globals['_PROCESSMESSAGE']._serialized_start=185
  _globals['_PROCESSMESSAGE']._serialized_end=338
  _globals['_MONITORMESSAGE']._serialized_start=341
  _globals['_MONITORMESSAGE']._serialized_end=470
  _globals['_PROCMONITORREQUEST']._serialized_start=472
  _globals['_PROCMONITORREQUEST']._serialized_end=523
  _globals['_SHELLEXE']._serialized_start=525
  _globals['_SHELLEXE']._serialized_end=553
  _globals['_GRPCSERVICE']._serialized_start=556
  _globals['_GRPCSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
